aws_region                    = "sa-east-1"
aws_profile                   = "tadeumendonca-vpc"
customer_workload_name        = "tadeumendonca.io"
customer_workload_owner       = "tadeu.mendonca"
customer_workload_sponsor     = "tadeu.mendonca"
customer_workload_environment = "main"