aws_region                    = "us-east-1"
aws_profile                   = ""
customer_workload_name        = "tadeumendonca.io"
customer_workload_owner       = "tadeu.mendonca"
customer_workload_sponsor     = "tadeu.mendonca"
customer_workload_environment = "main"